### PR TITLE
Fix DevTools window not appearing, if we have an error in the composition.

### LINKED ISSUE #322: App fails when restart after exception
If some exception is thrown and shown in hot reload mod and you click to "Reload" then application is restarted and failed, gradle task is stopped.

https://github.com/user-attachments/assets/db49a861-cfd8-4641-b573-3fc0c4fe8942

### PR DESCRIPTION
**Pull request by pjBooms**
Fixes #322

If we have an error in the composition we may not launch LaunchedEffects. 
Previously we had a logic for window management (synchronizing the app window with the devtool window) in a LaunchedEffect that could be skipped in case of errors, thus devtools was not notified about app window appearing and did not show devtools window.

Here we fix it launching the required logic instantly.

### CODE REVIEW

File: hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt [hunk 1]
```diff
@@ -33,121 +27,124 @@ import java.awt.event.WindowEvent
...
-
-        /* Synchronize windows state with orchestration */
-        orchestration.subtask {
-            windowState.consumeAsFlow().conflate().collect { state ->
-                orchestration.update(WindowsState) { current ->
-                    val windows = if (state == null) current.windows - windowId
-                    else current.windows + (windowId to state)
-                    WindowsState(windows)
-                }
+    curWindowId?.let {
```
Comment (AbdullinAM) [inline hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: Although this approach works good for one window, I think it will break if a single application launches multiple windows

File: hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt [hunk 2]
```diff
@@ -33,121 +27,124 @@ import java.awt.event.WindowEvent
 
 private val logger = createLogger()
 
-@Composable
+private var curWindowId: WindowId? = null
+private var curWindow: Window? = null
```
Comment (sellmair) [inline hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: There can be multiple windows, so I think this code is violating that assumption. 
As a second note: I think holding a strong reference to an object like window, statically might be a bad idea.

File: hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt [hunk 3]
```diff
@@ -33,121 +27,124 @@ import java.awt.event.WindowEvent
...
+    }
+
+    val windowId = WindowId.create()
+    curWindowId = windowId
+    curWindow = window
+
+    val windowState = Channel<WindowState?>(Channel.CONFLATED)
+
+    /* Synchronize windows state with orchestration */
+    orchestration.subtask {
```
Comment (sellmair) [inline hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: This now will launch one subtask for each composition, which can be a lot.

Comment (AbdullinAM) [inline hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: I have a concern that this `subtask` will never finish execution.

Previously we had a clean-up procedure: removed listeners (I'm not sure if its necessary) and closed the channel, which lead to the `subtask` completion. Now the state is never closed and the subtask is never finished. 

Realistically, 99% of the applications have only one window and stop the process when it is closed. Can we at least test this scenario and see if there is a 'leak' and how bad it is?

**Review by AbdullinAM — CHANGES_REQUESTED** [review]

File: hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt (hunk 3 above)
Comment (pjBooms) [reply hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: The function is called only once in the fix, so it is not the case.

Comment (sellmair) [reply hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: Error was captured in composition while live edit was enabled.
java.lang.IllegalStateException: unexpected window re-initialization

image

The function is called within a `@Composable` function, so it can be called as often as with every frame (roughly).

File: hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt (hunk 2 above)
Comment (pjBooms) [reply hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: Rewrote. Please take a look.

File: hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt (hunk 3 above)
Comment (pjBooms) [reply hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: But we returned immediately from `startWindowManager`  not reaching this point (` orchestration.subtask` was called only once for a window). Anyway, I rewrote it.

File: hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt (hunk 1 above)
Comment (pjBooms) [reply hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: addressed

File: hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt (hunk 3 above)
Comment (pjBooms) [reply hot-reload-runtime-jvm/src/main/kotlin/org/jetbrains/compose/reload/jvm/window.kt]: Addressed. Now we do the cleanup  on the composition exit.

**Review by AbdullinAM — APPROVED** [review]
Nice! I like how the fixed version looks 🔥
